# -*- coding: utf-8 -*-
"""python_trivia_game.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lilQWxik3ieyJJ5KCpstmj5Omhwwd5EA
"""

# Building a trivia game

# Create a dictionary of all of the questions in the game
dic_questions={"What is the keyword to define a function in python?":"def",
      "Which data type is used to store True or False values?":"bool",
      "Which symbol is used to comment in python?":"#",
      "What function is used to get input from the user?":"input",
      "What do you use to write a for loop in python":"for"
}

#random module is imported to randomly pick questions from the dictionary
import random
def trivia_game():
  score=0
  # Convert the dictionary keys into a list to allow iteration over them
  list_questions=list(dic_questions.keys())
  # This picks two random questions from the list
  selected_questions=random.sample(list_questions,2)
  # allows questions to be displayed with index
  # 1 is added to the index as I want the index to start from 1
  for idx,question in enumerate(selected_questions):
    print(f"{idx+1}.{question}")
    # Convert input to lowercase for easier comparison
    # In case the user enters space strip was used
    answer=input("Enter your anwer: ").lower().strip()
    correct_answer=dic_questions[question]

    if correct_answer==answer:
      print(f"Good job! Your answer is correct.")
      score+=1
    else:
      print(f"Your answer is incorrect.The correct answer is {correct_answer}")

  print(f"Game over!. Your final score is {score}/2")

trivia_game()